### ISSUE TITLE
Error:EPERm, operation not permitted

### ISSUE THREAD

**Issue by napcat** [LeZuse/node-flatten-deps#2]
When trying to flatten a project:

fs.js:554
  return binding.rename(pathModule._makeLong(oldPath),
                 ^
Error: EPERM, operation not permitted 'D:\TFS\AppRoot\App\node_modules\adm-zip'
  at Object.fs.renameSync (fs.js:554:18)
  at moveIfPossible (C:\Users\myuser\AppData\Roaming\npm\node_modules\flatten-deps\lib\flatten.coffee:54:10)
  at run (C:\Users\hats\AppData\Roaming\npm\node_modules\flatten-deps\lib\flatten.coffee:69:9)
  at Object.<anonymous> (C:\Users\hats\AppData\Roaming\npm\node_modules\flatten-deps\bin\flatten-deps:3:25)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

**Comment by LeZuse** [comment]
Do you have the necessary rights? What was the use case? Can you provide more details (platform, node/npm ver, etc) ?

**Comment by LeZuse** [comment]
Since I don't have any more info, I will close this issue until there's more.
